version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    depends_on:
      - node-backend

  node-backend:
    build:
      context: ./backend/node-service
      dockerfile: Dockerfile.dev
    ports:
      - "3001:3001"
    volumes:
      - ./backend/node-service:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    depends_on:
      - python-backend

  python-backend:
    build:
      context: ./backend/python-service
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
    volumes:
      - ./backend/python-service:/app
    environment:
      - PYTHONUNBUFFERED=1
